# Generated by Django 4.0.1 on 2022-01-30 01:10

from django.db import migrations, models
import shock.models


class Migration(migrations.Migration):

    dependencies = [
        ('shock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controllerstate',
            old_name='power_level',
            new_name='shock_power',
        ),
        migrations.AddField(
            model_name='controllerstate',
            name='mode',
            field=models.IntegerField(default=shock.models.Mode['SHOCK']),
        ),
        migrations.AddField(
            model_name='controllerstate',
            name='vibrate_power',
            field=models.IntegerField(default=0),
        ),
    ]
