# Generated by Django 4.0.1 on 2022-01-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shock', '0002_rename_power_level_controllerstate_shock_power_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controllerstate',
            old_name='vibrate_power',
            new_name='vibration_power',
        ),
    ]
